import { GoogleButton } from "@/components/SignIn/GoogleButton";
import { SignInForm } from "@/components/SignIn/SignInForm";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sign In | NextJS",
  description: "Generated by create next app",
};

export default async function SignIn() {
  return (
    <div className="stack">
      <h1>Sign In</h1>
      <GoogleButton />
      <SignInForm />
    </div>
  );
}
