import { TheHeader } from "@/components/TheHeader";
import { Providers } from "@/components/Providers";
import TheFooter from "@/components/TheFooter";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Home | NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <TheHeader />
          <main>{children}</main>
          <TheFooter />
        </Providers>
      </body>
    </html>
  );
}
